let sc = document.createElement('script');
sc.innerHTML = ""
+ "function data2clipboard(data) {"
+ "  let tmp_elem = document.createElement('textarea');"
+ "  tmp_elem.value = data;"
+ "  document.body.appendChild(tmp_elem);"
+ "  tmp_elem.select();"
+ "   document.execCommand('copy');"
+ "}"
+ "function copy_img_urls() {"
+ "    try {"
+ "      /* 検索しているキーワードを取得 */"
+ "      let query = document.getElementById('lst-ib').value;"
+ "      /* 画像URLを配列で取得 */"
+ "      let img_urls = [];"
+ "      for (let img_elem of document.getElementsByClassName('rg_l')) {"
+ "        try {"
+ "          let qs = img_elem.href.split('?')[1];"
+ "          let imgurl_k_v = qs.split('&')[0];"
+ "          let img_url = imgurl_k_v.split('=')[1];"
+ "          img_urls.push(query + '\\t' + decodeURIComponent(img_url));"
+ "        } catch (e) {"
+ "        }"
+ "      }"
+ "      /* キーワード<tab>URL をクリップボードにコピー */"
+ "      data2clipboard(img_urls.join('\\n'));"
+ "    } catch (e) {"
+ "      alert(e.stack);"
+ "      console.log(e);"
+ "    }"
+ "}"
+ "let fb = document.createElement('div');"
+ "fb.innerHTML = '<button onclick=\"copy_img_urls()\">copy img urls</button>';"
+ "document.getElementById('fbar').appendChild(fb);";
document.getElementById('fbar').appendChild(sc);
